version: 2.1

defaults: &defaults
  docker:
    - image: node:current-alpine3.12
  working_directory: ~/project

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: "Run setup"
          command: "npm run setup"
      - run:
          name: "Lint code"
          command: "npm run lint"

workflows:
  ci-workflow:
    jobs:
      - build
