version: 2.1

defaults: &defaults
  docker:
    - image: alpine:latest
  working_directory: ~/project

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: "NPM install"
          command: "npm i"
      - run:
          name: "Lint code"
          command: "npm run lint"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
